/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package isel.mpd.painter0.app;

import isel.mpd.painter0.view.PainterFrame;

public class App {

    public static void main(String[] args) {

        PainterFrame painter = new PainterFrame();
        painter.setVisible(true);
    }
}
