/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package painter.app;

import isel.mpd.painter0.utils.RandomUtils;
import org.junit.jupiter.api.Test;

import java.awt.*;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

class MessageUtilsTest {
    @Test void testGetMessage() {

    }
}
